// Generated by gencpp from file seed_robotics/AllJoints.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_ALLJOINTS_H
#define SEED_ROBOTICS_MESSAGE_ALLJOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <seed_robotics/LoneJoint.h>

namespace seed_robotics
{
template <class ContainerAllocator>
struct AllJoints_
{
  typedef AllJoints_<ContainerAllocator> Type;

  AllJoints_()
    : header()
    , length(0)
    , joints()  {
    }
  AllJoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , length(0)
    , joints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _length_type;
  _length_type length;

   typedef std::vector< ::seed_robotics::LoneJoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::seed_robotics::LoneJoint_<ContainerAllocator> >::other >  _joints_type;
  _joints_type joints;





  typedef boost::shared_ptr< ::seed_robotics::AllJoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seed_robotics::AllJoints_<ContainerAllocator> const> ConstPtr;

}; // struct AllJoints_

typedef ::seed_robotics::AllJoints_<std::allocator<void> > AllJoints;

typedef boost::shared_ptr< ::seed_robotics::AllJoints > AllJointsPtr;
typedef boost::shared_ptr< ::seed_robotics::AllJoints const> AllJointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seed_robotics::AllJoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seed_robotics::AllJoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seed_robotics::AllJoints_<ContainerAllocator1> & lhs, const ::seed_robotics::AllJoints_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.length == rhs.length &&
    lhs.joints == rhs.joints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seed_robotics::AllJoints_<ContainerAllocator1> & lhs, const ::seed_robotics::AllJoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seed_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::AllJoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::AllJoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::AllJoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::AllJoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::AllJoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::AllJoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seed_robotics::AllJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c243bafdaa2962b834d336b24525b43";
  }

  static const char* value(const ::seed_robotics::AllJoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c243bafdaa2962bULL;
  static const uint64_t static_value2 = 0x834d336b24525b43ULL;
};

template<class ContainerAllocator>
struct DataType< ::seed_robotics::AllJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_robotics/AllJoints";
  }

  static const char* value(const ::seed_robotics::AllJoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seed_robotics::AllJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 length\n"
"seed_robotics/LoneJoint[] joints\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: seed_robotics/LoneJoint\n"
"string name\n"
"uint8 bus_id\n"
"uint8 stiffness\n"
"uint8 stress_level\n"
"uint16 target_position\n"
"uint16 target_speed\n"
"uint16 torque_limit\n"
"uint16 present_position\n"
"int16 present_speed\n"
"uint8 temperature\n"
"uint8 moving\n"
"uint8 HW_error_condition\n"
"int16 current\n"
;
  }

  static const char* value(const ::seed_robotics::AllJoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seed_robotics::AllJoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.length);
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AllJoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seed_robotics::AllJoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seed_robotics::AllJoints_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "length: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.length);
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::seed_robotics::LoneJoint_<ContainerAllocator> >::stream(s, indent + "    ", v.joints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_ALLJOINTS_H
