// Generated by gencpp from file seed_robotics/AllMainBoards.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_ALLMAINBOARDS_H
#define SEED_ROBOTICS_MESSAGE_ALLMAINBOARDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <seed_robotics/LoneMainBoard.h>

namespace seed_robotics
{
template <class ContainerAllocator>
struct AllMainBoards_
{
  typedef AllMainBoards_<ContainerAllocator> Type;

  AllMainBoards_()
    : header()
    , length(0)
    , boards()  {
    }
  AllMainBoards_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , length(0)
    , boards(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _length_type;
  _length_type length;

   typedef std::vector< ::seed_robotics::LoneMainBoard_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::seed_robotics::LoneMainBoard_<ContainerAllocator> >::other >  _boards_type;
  _boards_type boards;





  typedef boost::shared_ptr< ::seed_robotics::AllMainBoards_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seed_robotics::AllMainBoards_<ContainerAllocator> const> ConstPtr;

}; // struct AllMainBoards_

typedef ::seed_robotics::AllMainBoards_<std::allocator<void> > AllMainBoards;

typedef boost::shared_ptr< ::seed_robotics::AllMainBoards > AllMainBoardsPtr;
typedef boost::shared_ptr< ::seed_robotics::AllMainBoards const> AllMainBoardsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seed_robotics::AllMainBoards_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seed_robotics::AllMainBoards_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seed_robotics::AllMainBoards_<ContainerAllocator1> & lhs, const ::seed_robotics::AllMainBoards_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.length == rhs.length &&
    lhs.boards == rhs.boards;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seed_robotics::AllMainBoards_<ContainerAllocator1> & lhs, const ::seed_robotics::AllMainBoards_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seed_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::AllMainBoards_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::AllMainBoards_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::AllMainBoards_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::AllMainBoards_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::AllMainBoards_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::AllMainBoards_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seed_robotics::AllMainBoards_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abd5fb0a6ebd19a335f879c68cdd135f";
  }

  static const char* value(const ::seed_robotics::AllMainBoards_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabd5fb0a6ebd19a3ULL;
  static const uint64_t static_value2 = 0x35f879c68cdd135fULL;
};

template<class ContainerAllocator>
struct DataType< ::seed_robotics::AllMainBoards_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_robotics/AllMainBoards";
  }

  static const char* value(const ::seed_robotics::AllMainBoards_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seed_robotics::AllMainBoards_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 length\n"
"seed_robotics/LoneMainBoard[] boards\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: seed_robotics/LoneMainBoard\n"
"uint8 id\n"
"string name\n"
"uint16 palm_IR_sensor\n"
"uint16 capacitive_sensor_1\n"
"uint16 capacitive_sensor_2\n"
;
  }

  static const char* value(const ::seed_robotics::AllMainBoards_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seed_robotics::AllMainBoards_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.length);
      stream.next(m.boards);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AllMainBoards_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seed_robotics::AllMainBoards_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seed_robotics::AllMainBoards_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "length: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.length);
    s << indent << "boards[]" << std::endl;
    for (size_t i = 0; i < v.boards.size(); ++i)
    {
      s << indent << "  boards[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::seed_robotics::LoneMainBoard_<ContainerAllocator> >::stream(s, indent + "    ", v.boards[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_ALLMAINBOARDS_H
