// Generated by gencpp from file seed_robotics/BulkGetItem.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_BULKGETITEM_H
#define SEED_ROBOTICS_MESSAGE_BULKGETITEM_H

#include <ros/service_traits.h>


#include <seed_robotics/BulkGetItemRequest.h>
#include <seed_robotics/BulkGetItemResponse.h>


namespace seed_robotics
{

struct BulkGetItem
{

typedef BulkGetItemRequest Request;
typedef BulkGetItemResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BulkGetItem
} // namespace seed_robotics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::seed_robotics::BulkGetItem > {
  static const char* value()
  {
    return "f0b74b4d53178e0d0ede26a30b687544";
  }

  static const char* value(const ::seed_robotics::BulkGetItem&) { return value(); }
};

template<>
struct DataType< ::seed_robotics::BulkGetItem > {
  static const char* value()
  {
    return "seed_robotics/BulkGetItem";
  }

  static const char* value(const ::seed_robotics::BulkGetItem&) { return value(); }
};


// service_traits::MD5Sum< ::seed_robotics::BulkGetItemRequest> should match
// service_traits::MD5Sum< ::seed_robotics::BulkGetItem >
template<>
struct MD5Sum< ::seed_robotics::BulkGetItemRequest>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::BulkGetItem >::value();
  }
  static const char* value(const ::seed_robotics::BulkGetItemRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::BulkGetItemRequest> should match
// service_traits::DataType< ::seed_robotics::BulkGetItem >
template<>
struct DataType< ::seed_robotics::BulkGetItemRequest>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::BulkGetItem >::value();
  }
  static const char* value(const ::seed_robotics::BulkGetItemRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::seed_robotics::BulkGetItemResponse> should match
// service_traits::MD5Sum< ::seed_robotics::BulkGetItem >
template<>
struct MD5Sum< ::seed_robotics::BulkGetItemResponse>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::BulkGetItem >::value();
  }
  static const char* value(const ::seed_robotics::BulkGetItemResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::BulkGetItemResponse> should match
// service_traits::DataType< ::seed_robotics::BulkGetItem >
template<>
struct DataType< ::seed_robotics::BulkGetItemResponse>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::BulkGetItem >::value();
  }
  static const char* value(const ::seed_robotics::BulkGetItemResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_BULKGETITEM_H
