// Generated by gencpp from file seed_robotics/GetCurrent.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_GETCURRENT_H
#define SEED_ROBOTICS_MESSAGE_GETCURRENT_H

#include <ros/service_traits.h>


#include <seed_robotics/GetCurrentRequest.h>
#include <seed_robotics/GetCurrentResponse.h>


namespace seed_robotics
{

struct GetCurrent
{

typedef GetCurrentRequest Request;
typedef GetCurrentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCurrent
} // namespace seed_robotics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::seed_robotics::GetCurrent > {
  static const char* value()
  {
    return "e5afeed341ec02e41760a747f3e580ae";
  }

  static const char* value(const ::seed_robotics::GetCurrent&) { return value(); }
};

template<>
struct DataType< ::seed_robotics::GetCurrent > {
  static const char* value()
  {
    return "seed_robotics/GetCurrent";
  }

  static const char* value(const ::seed_robotics::GetCurrent&) { return value(); }
};


// service_traits::MD5Sum< ::seed_robotics::GetCurrentRequest> should match
// service_traits::MD5Sum< ::seed_robotics::GetCurrent >
template<>
struct MD5Sum< ::seed_robotics::GetCurrentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::GetCurrent >::value();
  }
  static const char* value(const ::seed_robotics::GetCurrentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::GetCurrentRequest> should match
// service_traits::DataType< ::seed_robotics::GetCurrent >
template<>
struct DataType< ::seed_robotics::GetCurrentRequest>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::GetCurrent >::value();
  }
  static const char* value(const ::seed_robotics::GetCurrentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::seed_robotics::GetCurrentResponse> should match
// service_traits::MD5Sum< ::seed_robotics::GetCurrent >
template<>
struct MD5Sum< ::seed_robotics::GetCurrentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::GetCurrent >::value();
  }
  static const char* value(const ::seed_robotics::GetCurrentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::GetCurrentResponse> should match
// service_traits::DataType< ::seed_robotics::GetCurrent >
template<>
struct DataType< ::seed_robotics::GetCurrentResponse>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::GetCurrent >::value();
  }
  static const char* value(const ::seed_robotics::GetCurrentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_GETCURRENT_H
