// Generated by gencpp from file seed_robotics/GetGoalPosition.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_GETGOALPOSITION_H
#define SEED_ROBOTICS_MESSAGE_GETGOALPOSITION_H

#include <ros/service_traits.h>


#include <seed_robotics/GetGoalPositionRequest.h>
#include <seed_robotics/GetGoalPositionResponse.h>


namespace seed_robotics
{

struct GetGoalPosition
{

typedef GetGoalPositionRequest Request;
typedef GetGoalPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGoalPosition
} // namespace seed_robotics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::seed_robotics::GetGoalPosition > {
  static const char* value()
  {
    return "c6430525f1b226ec7b2120ff40297feb";
  }

  static const char* value(const ::seed_robotics::GetGoalPosition&) { return value(); }
};

template<>
struct DataType< ::seed_robotics::GetGoalPosition > {
  static const char* value()
  {
    return "seed_robotics/GetGoalPosition";
  }

  static const char* value(const ::seed_robotics::GetGoalPosition&) { return value(); }
};


// service_traits::MD5Sum< ::seed_robotics::GetGoalPositionRequest> should match
// service_traits::MD5Sum< ::seed_robotics::GetGoalPosition >
template<>
struct MD5Sum< ::seed_robotics::GetGoalPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::GetGoalPosition >::value();
  }
  static const char* value(const ::seed_robotics::GetGoalPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::GetGoalPositionRequest> should match
// service_traits::DataType< ::seed_robotics::GetGoalPosition >
template<>
struct DataType< ::seed_robotics::GetGoalPositionRequest>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::GetGoalPosition >::value();
  }
  static const char* value(const ::seed_robotics::GetGoalPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::seed_robotics::GetGoalPositionResponse> should match
// service_traits::MD5Sum< ::seed_robotics::GetGoalPosition >
template<>
struct MD5Sum< ::seed_robotics::GetGoalPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::GetGoalPosition >::value();
  }
  static const char* value(const ::seed_robotics::GetGoalPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::GetGoalPositionResponse> should match
// service_traits::DataType< ::seed_robotics::GetGoalPosition >
template<>
struct DataType< ::seed_robotics::GetGoalPositionResponse>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::GetGoalPosition >::value();
  }
  static const char* value(const ::seed_robotics::GetGoalPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_GETGOALPOSITION_H
