// Generated by gencpp from file seed_robotics/GetGoalVelocity.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_GETGOALVELOCITY_H
#define SEED_ROBOTICS_MESSAGE_GETGOALVELOCITY_H

#include <ros/service_traits.h>


#include <seed_robotics/GetGoalVelocityRequest.h>
#include <seed_robotics/GetGoalVelocityResponse.h>


namespace seed_robotics
{

struct GetGoalVelocity
{

typedef GetGoalVelocityRequest Request;
typedef GetGoalVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGoalVelocity
} // namespace seed_robotics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::seed_robotics::GetGoalVelocity > {
  static const char* value()
  {
    return "176f1ed56ee1f0eee6e6a7fc38e4f377";
  }

  static const char* value(const ::seed_robotics::GetGoalVelocity&) { return value(); }
};

template<>
struct DataType< ::seed_robotics::GetGoalVelocity > {
  static const char* value()
  {
    return "seed_robotics/GetGoalVelocity";
  }

  static const char* value(const ::seed_robotics::GetGoalVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::seed_robotics::GetGoalVelocityRequest> should match
// service_traits::MD5Sum< ::seed_robotics::GetGoalVelocity >
template<>
struct MD5Sum< ::seed_robotics::GetGoalVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::GetGoalVelocity >::value();
  }
  static const char* value(const ::seed_robotics::GetGoalVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::GetGoalVelocityRequest> should match
// service_traits::DataType< ::seed_robotics::GetGoalVelocity >
template<>
struct DataType< ::seed_robotics::GetGoalVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::GetGoalVelocity >::value();
  }
  static const char* value(const ::seed_robotics::GetGoalVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::seed_robotics::GetGoalVelocityResponse> should match
// service_traits::MD5Sum< ::seed_robotics::GetGoalVelocity >
template<>
struct MD5Sum< ::seed_robotics::GetGoalVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::GetGoalVelocity >::value();
  }
  static const char* value(const ::seed_robotics::GetGoalVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::GetGoalVelocityResponse> should match
// service_traits::DataType< ::seed_robotics::GetGoalVelocity >
template<>
struct DataType< ::seed_robotics::GetGoalVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::GetGoalVelocity >::value();
  }
  static const char* value(const ::seed_robotics::GetGoalVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_GETGOALVELOCITY_H
