// Generated by gencpp from file seed_robotics/GetGoalPositionResponse.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_GETGOALPOSITIONRESPONSE_H
#define SEED_ROBOTICS_MESSAGE_GETGOALPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace seed_robotics
{
template <class ContainerAllocator>
struct GetGoalPositionResponse_
{
  typedef GetGoalPositionResponse_<ContainerAllocator> Type;

  GetGoalPositionResponse_()
    : goal_position(0)  {
    }
  GetGoalPositionResponse_(const ContainerAllocator& _alloc)
    : goal_position(0)  {
  (void)_alloc;
    }



   typedef int16_t _goal_position_type;
  _goal_position_type goal_position;





  typedef boost::shared_ptr< ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetGoalPositionResponse_

typedef ::seed_robotics::GetGoalPositionResponse_<std::allocator<void> > GetGoalPositionResponse;

typedef boost::shared_ptr< ::seed_robotics::GetGoalPositionResponse > GetGoalPositionResponsePtr;
typedef boost::shared_ptr< ::seed_robotics::GetGoalPositionResponse const> GetGoalPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator1> & lhs, const ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.goal_position == rhs.goal_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator1> & lhs, const ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seed_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c9a3b382e7667f938f73ab1c6b39363";
  }

  static const char* value(const ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c9a3b382e7667f9ULL;
  static const uint64_t static_value2 = 0x38f73ab1c6b39363ULL;
};

template<class ContainerAllocator>
struct DataType< ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_robotics/GetGoalPositionResponse";
  }

  static const char* value(const ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 goal_position\n"
"\n"
;
  }

  static const char* value(const ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGoalPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seed_robotics::GetGoalPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "goal_position: ";
    Printer<int16_t>::stream(s, indent + "  ", v.goal_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_GETGOALPOSITIONRESPONSE_H
