// Generated by gencpp from file seed_robotics/GetGoalVelocityResponse.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_GETGOALVELOCITYRESPONSE_H
#define SEED_ROBOTICS_MESSAGE_GETGOALVELOCITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace seed_robotics
{
template <class ContainerAllocator>
struct GetGoalVelocityResponse_
{
  typedef GetGoalVelocityResponse_<ContainerAllocator> Type;

  GetGoalVelocityResponse_()
    : goal_velocity(0)  {
    }
  GetGoalVelocityResponse_(const ContainerAllocator& _alloc)
    : goal_velocity(0)  {
  (void)_alloc;
    }



   typedef int16_t _goal_velocity_type;
  _goal_velocity_type goal_velocity;





  typedef boost::shared_ptr< ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetGoalVelocityResponse_

typedef ::seed_robotics::GetGoalVelocityResponse_<std::allocator<void> > GetGoalVelocityResponse;

typedef boost::shared_ptr< ::seed_robotics::GetGoalVelocityResponse > GetGoalVelocityResponsePtr;
typedef boost::shared_ptr< ::seed_robotics::GetGoalVelocityResponse const> GetGoalVelocityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator1> & lhs, const ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.goal_velocity == rhs.goal_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator1> & lhs, const ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seed_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79e0781e64d99d67b089928030c2a256";
  }

  static const char* value(const ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79e0781e64d99d67ULL;
  static const uint64_t static_value2 = 0xb089928030c2a256ULL;
};

template<class ContainerAllocator>
struct DataType< ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_robotics/GetGoalVelocityResponse";
  }

  static const char* value(const ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 goal_velocity\n"
"\n"
;
  }

  static const char* value(const ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGoalVelocityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seed_robotics::GetGoalVelocityResponse_<ContainerAllocator>& v)
  {
    s << indent << "goal_velocity: ";
    Printer<int16_t>::stream(s, indent + "  ", v.goal_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_GETGOALVELOCITYRESPONSE_H
