// Generated by gencpp from file seed_robotics/GetPresentVelocity.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_GETPRESENTVELOCITY_H
#define SEED_ROBOTICS_MESSAGE_GETPRESENTVELOCITY_H

#include <ros/service_traits.h>


#include <seed_robotics/GetPresentVelocityRequest.h>
#include <seed_robotics/GetPresentVelocityResponse.h>


namespace seed_robotics
{

struct GetPresentVelocity
{

typedef GetPresentVelocityRequest Request;
typedef GetPresentVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPresentVelocity
} // namespace seed_robotics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::seed_robotics::GetPresentVelocity > {
  static const char* value()
  {
    return "2414cb2e4ff96bd9445295b7a5e4de44";
  }

  static const char* value(const ::seed_robotics::GetPresentVelocity&) { return value(); }
};

template<>
struct DataType< ::seed_robotics::GetPresentVelocity > {
  static const char* value()
  {
    return "seed_robotics/GetPresentVelocity";
  }

  static const char* value(const ::seed_robotics::GetPresentVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::seed_robotics::GetPresentVelocityRequest> should match
// service_traits::MD5Sum< ::seed_robotics::GetPresentVelocity >
template<>
struct MD5Sum< ::seed_robotics::GetPresentVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::GetPresentVelocity >::value();
  }
  static const char* value(const ::seed_robotics::GetPresentVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::GetPresentVelocityRequest> should match
// service_traits::DataType< ::seed_robotics::GetPresentVelocity >
template<>
struct DataType< ::seed_robotics::GetPresentVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::GetPresentVelocity >::value();
  }
  static const char* value(const ::seed_robotics::GetPresentVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::seed_robotics::GetPresentVelocityResponse> should match
// service_traits::MD5Sum< ::seed_robotics::GetPresentVelocity >
template<>
struct MD5Sum< ::seed_robotics::GetPresentVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::GetPresentVelocity >::value();
  }
  static const char* value(const ::seed_robotics::GetPresentVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::GetPresentVelocityResponse> should match
// service_traits::DataType< ::seed_robotics::GetPresentVelocity >
template<>
struct DataType< ::seed_robotics::GetPresentVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::GetPresentVelocity >::value();
  }
  static const char* value(const ::seed_robotics::GetPresentVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_GETPRESENTVELOCITY_H
