// Generated by gencpp from file seed_robotics/GetPosVelocityResponse.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_GETPOSVELOCITYRESPONSE_H
#define SEED_ROBOTICS_MESSAGE_GETPOSVELOCITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace seed_robotics
{
template <class ContainerAllocator>
struct GetPosVelocityResponse_
{
  typedef GetPosVelocityResponse_<ContainerAllocator> Type;

  GetPosVelocityResponse_()
    : present_position(0)
    , goal_position(0)
    , present_velocity(0)
    , goal_velocity(0)  {
    }
  GetPosVelocityResponse_(const ContainerAllocator& _alloc)
    : present_position(0)
    , goal_position(0)
    , present_velocity(0)
    , goal_velocity(0)  {
  (void)_alloc;
    }



   typedef int16_t _present_position_type;
  _present_position_type present_position;

   typedef int16_t _goal_position_type;
  _goal_position_type goal_position;

   typedef int16_t _present_velocity_type;
  _present_velocity_type present_velocity;

   typedef int16_t _goal_velocity_type;
  _goal_velocity_type goal_velocity;





  typedef boost::shared_ptr< ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPosVelocityResponse_

typedef ::seed_robotics::GetPosVelocityResponse_<std::allocator<void> > GetPosVelocityResponse;

typedef boost::shared_ptr< ::seed_robotics::GetPosVelocityResponse > GetPosVelocityResponsePtr;
typedef boost::shared_ptr< ::seed_robotics::GetPosVelocityResponse const> GetPosVelocityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator1> & lhs, const ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.present_position == rhs.present_position &&
    lhs.goal_position == rhs.goal_position &&
    lhs.present_velocity == rhs.present_velocity &&
    lhs.goal_velocity == rhs.goal_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator1> & lhs, const ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seed_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f887058957ab1477fd2dccabad72c13";
  }

  static const char* value(const ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f887058957ab147ULL;
  static const uint64_t static_value2 = 0x7fd2dccabad72c13ULL;
};

template<class ContainerAllocator>
struct DataType< ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_robotics/GetPosVelocityResponse";
  }

  static const char* value(const ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 present_position\n"
"int16 goal_position\n"
"int16 present_velocity\n"
"int16 goal_velocity\n"
"\n"
;
  }

  static const char* value(const ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.present_position);
      stream.next(m.goal_position);
      stream.next(m.present_velocity);
      stream.next(m.goal_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPosVelocityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seed_robotics::GetPosVelocityResponse_<ContainerAllocator>& v)
  {
    s << indent << "present_position: ";
    Printer<int16_t>::stream(s, indent + "  ", v.present_position);
    s << indent << "goal_position: ";
    Printer<int16_t>::stream(s, indent + "  ", v.goal_position);
    s << indent << "present_velocity: ";
    Printer<int16_t>::stream(s, indent + "  ", v.present_velocity);
    s << indent << "goal_velocity: ";
    Printer<int16_t>::stream(s, indent + "  ", v.goal_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_GETPOSVELOCITYRESPONSE_H
