// Generated by gencpp from file seed_robotics/GetPresentPositionResponse.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_GETPRESENTPOSITIONRESPONSE_H
#define SEED_ROBOTICS_MESSAGE_GETPRESENTPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace seed_robotics
{
template <class ContainerAllocator>
struct GetPresentPositionResponse_
{
  typedef GetPresentPositionResponse_<ContainerAllocator> Type;

  GetPresentPositionResponse_()
    : present_position(0)  {
    }
  GetPresentPositionResponse_(const ContainerAllocator& _alloc)
    : present_position(0)  {
  (void)_alloc;
    }



   typedef int16_t _present_position_type;
  _present_position_type present_position;





  typedef boost::shared_ptr< ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPresentPositionResponse_

typedef ::seed_robotics::GetPresentPositionResponse_<std::allocator<void> > GetPresentPositionResponse;

typedef boost::shared_ptr< ::seed_robotics::GetPresentPositionResponse > GetPresentPositionResponsePtr;
typedef boost::shared_ptr< ::seed_robotics::GetPresentPositionResponse const> GetPresentPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator1> & lhs, const ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.present_position == rhs.present_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator1> & lhs, const ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seed_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2e7108fbe09c747ed9275889fd07b92";
  }

  static const char* value(const ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2e7108fbe09c747ULL;
  static const uint64_t static_value2 = 0xed9275889fd07b92ULL;
};

template<class ContainerAllocator>
struct DataType< ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_robotics/GetPresentPositionResponse";
  }

  static const char* value(const ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 present_position\n"
"\n"
;
  }

  static const char* value(const ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.present_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPresentPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seed_robotics::GetPresentPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "present_position: ";
    Printer<int16_t>::stream(s, indent + "  ", v.present_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_GETPRESENTPOSITIONRESPONSE_H
