// Generated by gencpp from file seed_robotics/GetPresentPosition.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_GETPRESENTPOSITION_H
#define SEED_ROBOTICS_MESSAGE_GETPRESENTPOSITION_H

#include <ros/service_traits.h>


#include <seed_robotics/GetPresentPositionRequest.h>
#include <seed_robotics/GetPresentPositionResponse.h>


namespace seed_robotics
{

struct GetPresentPosition
{

typedef GetPresentPositionRequest Request;
typedef GetPresentPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPresentPosition
} // namespace seed_robotics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::seed_robotics::GetPresentPosition > {
  static const char* value()
  {
    return "d91c2c73f7e02d744ba302aa9965c4c8";
  }

  static const char* value(const ::seed_robotics::GetPresentPosition&) { return value(); }
};

template<>
struct DataType< ::seed_robotics::GetPresentPosition > {
  static const char* value()
  {
    return "seed_robotics/GetPresentPosition";
  }

  static const char* value(const ::seed_robotics::GetPresentPosition&) { return value(); }
};


// service_traits::MD5Sum< ::seed_robotics::GetPresentPositionRequest> should match
// service_traits::MD5Sum< ::seed_robotics::GetPresentPosition >
template<>
struct MD5Sum< ::seed_robotics::GetPresentPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::GetPresentPosition >::value();
  }
  static const char* value(const ::seed_robotics::GetPresentPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::GetPresentPositionRequest> should match
// service_traits::DataType< ::seed_robotics::GetPresentPosition >
template<>
struct DataType< ::seed_robotics::GetPresentPositionRequest>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::GetPresentPosition >::value();
  }
  static const char* value(const ::seed_robotics::GetPresentPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::seed_robotics::GetPresentPositionResponse> should match
// service_traits::MD5Sum< ::seed_robotics::GetPresentPosition >
template<>
struct MD5Sum< ::seed_robotics::GetPresentPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::GetPresentPosition >::value();
  }
  static const char* value(const ::seed_robotics::GetPresentPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::GetPresentPositionResponse> should match
// service_traits::DataType< ::seed_robotics::GetPresentPosition >
template<>
struct DataType< ::seed_robotics::GetPresentPositionResponse>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::GetPresentPosition >::value();
  }
  static const char* value(const ::seed_robotics::GetPresentPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_GETPRESENTPOSITION_H
