// Generated by gencpp from file seed_robotics/GetPosVelocity.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_GETPOSVELOCITY_H
#define SEED_ROBOTICS_MESSAGE_GETPOSVELOCITY_H

#include <ros/service_traits.h>


#include <seed_robotics/GetPosVelocityRequest.h>
#include <seed_robotics/GetPosVelocityResponse.h>


namespace seed_robotics
{

struct GetPosVelocity
{

typedef GetPosVelocityRequest Request;
typedef GetPosVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPosVelocity
} // namespace seed_robotics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::seed_robotics::GetPosVelocity > {
  static const char* value()
  {
    return "03d33e418b2174778dea8e5cd3831c82";
  }

  static const char* value(const ::seed_robotics::GetPosVelocity&) { return value(); }
};

template<>
struct DataType< ::seed_robotics::GetPosVelocity > {
  static const char* value()
  {
    return "seed_robotics/GetPosVelocity";
  }

  static const char* value(const ::seed_robotics::GetPosVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::seed_robotics::GetPosVelocityRequest> should match
// service_traits::MD5Sum< ::seed_robotics::GetPosVelocity >
template<>
struct MD5Sum< ::seed_robotics::GetPosVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::GetPosVelocity >::value();
  }
  static const char* value(const ::seed_robotics::GetPosVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::GetPosVelocityRequest> should match
// service_traits::DataType< ::seed_robotics::GetPosVelocity >
template<>
struct DataType< ::seed_robotics::GetPosVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::GetPosVelocity >::value();
  }
  static const char* value(const ::seed_robotics::GetPosVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::seed_robotics::GetPosVelocityResponse> should match
// service_traits::MD5Sum< ::seed_robotics::GetPosVelocity >
template<>
struct MD5Sum< ::seed_robotics::GetPosVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::GetPosVelocity >::value();
  }
  static const char* value(const ::seed_robotics::GetPosVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::GetPosVelocityResponse> should match
// service_traits::DataType< ::seed_robotics::GetPosVelocity >
template<>
struct DataType< ::seed_robotics::GetPosVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::GetPosVelocity >::value();
  }
  static const char* value(const ::seed_robotics::GetPosVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_GETPOSVELOCITY_H
