// Generated by gencpp from file seed_robotics/GetTemperature.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_GETTEMPERATURE_H
#define SEED_ROBOTICS_MESSAGE_GETTEMPERATURE_H

#include <ros/service_traits.h>


#include <seed_robotics/GetTemperatureRequest.h>
#include <seed_robotics/GetTemperatureResponse.h>


namespace seed_robotics
{

struct GetTemperature
{

typedef GetTemperatureRequest Request;
typedef GetTemperatureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTemperature
} // namespace seed_robotics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::seed_robotics::GetTemperature > {
  static const char* value()
  {
    return "89b37f343ec5c3e46049b037c86c9747";
  }

  static const char* value(const ::seed_robotics::GetTemperature&) { return value(); }
};

template<>
struct DataType< ::seed_robotics::GetTemperature > {
  static const char* value()
  {
    return "seed_robotics/GetTemperature";
  }

  static const char* value(const ::seed_robotics::GetTemperature&) { return value(); }
};


// service_traits::MD5Sum< ::seed_robotics::GetTemperatureRequest> should match
// service_traits::MD5Sum< ::seed_robotics::GetTemperature >
template<>
struct MD5Sum< ::seed_robotics::GetTemperatureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::GetTemperature >::value();
  }
  static const char* value(const ::seed_robotics::GetTemperatureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::GetTemperatureRequest> should match
// service_traits::DataType< ::seed_robotics::GetTemperature >
template<>
struct DataType< ::seed_robotics::GetTemperatureRequest>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::GetTemperature >::value();
  }
  static const char* value(const ::seed_robotics::GetTemperatureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::seed_robotics::GetTemperatureResponse> should match
// service_traits::MD5Sum< ::seed_robotics::GetTemperature >
template<>
struct MD5Sum< ::seed_robotics::GetTemperatureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::GetTemperature >::value();
  }
  static const char* value(const ::seed_robotics::GetTemperatureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::GetTemperatureResponse> should match
// service_traits::DataType< ::seed_robotics::GetTemperature >
template<>
struct DataType< ::seed_robotics::GetTemperatureResponse>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::GetTemperature >::value();
  }
  static const char* value(const ::seed_robotics::GetTemperatureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_GETTEMPERATURE_H
