// Generated by gencpp from file seed_robotics/GetTempCurrResponse.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_GETTEMPCURRRESPONSE_H
#define SEED_ROBOTICS_MESSAGE_GETTEMPCURRRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace seed_robotics
{
template <class ContainerAllocator>
struct GetTempCurrResponse_
{
  typedef GetTempCurrResponse_<ContainerAllocator> Type;

  GetTempCurrResponse_()
    : current(0)
    , temperature(0)  {
    }
  GetTempCurrResponse_(const ContainerAllocator& _alloc)
    : current(0)
    , temperature(0)  {
  (void)_alloc;
    }



   typedef int16_t _current_type;
  _current_type current;

   typedef int8_t _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::seed_robotics::GetTempCurrResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seed_robotics::GetTempCurrResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTempCurrResponse_

typedef ::seed_robotics::GetTempCurrResponse_<std::allocator<void> > GetTempCurrResponse;

typedef boost::shared_ptr< ::seed_robotics::GetTempCurrResponse > GetTempCurrResponsePtr;
typedef boost::shared_ptr< ::seed_robotics::GetTempCurrResponse const> GetTempCurrResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seed_robotics::GetTempCurrResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seed_robotics::GetTempCurrResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seed_robotics::GetTempCurrResponse_<ContainerAllocator1> & lhs, const ::seed_robotics::GetTempCurrResponse_<ContainerAllocator2> & rhs)
{
  return lhs.current == rhs.current &&
    lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seed_robotics::GetTempCurrResponse_<ContainerAllocator1> & lhs, const ::seed_robotics::GetTempCurrResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seed_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::GetTempCurrResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::GetTempCurrResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::GetTempCurrResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::GetTempCurrResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::GetTempCurrResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::GetTempCurrResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seed_robotics::GetTempCurrResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ae3f2dc226dc1f4c2bdafe4330e5666";
  }

  static const char* value(const ::seed_robotics::GetTempCurrResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ae3f2dc226dc1f4ULL;
  static const uint64_t static_value2 = 0xc2bdafe4330e5666ULL;
};

template<class ContainerAllocator>
struct DataType< ::seed_robotics::GetTempCurrResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_robotics/GetTempCurrResponse";
  }

  static const char* value(const ::seed_robotics::GetTempCurrResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seed_robotics::GetTempCurrResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 current\n"
"int8 temperature\n"
"\n"
;
  }

  static const char* value(const ::seed_robotics::GetTempCurrResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seed_robotics::GetTempCurrResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTempCurrResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seed_robotics::GetTempCurrResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seed_robotics::GetTempCurrResponse_<ContainerAllocator>& v)
  {
    s << indent << "current: ";
    Printer<int16_t>::stream(s, indent + "  ", v.current);
    s << indent << "temperature: ";
    Printer<int8_t>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_GETTEMPCURRRESPONSE_H
