// Generated by gencpp from file seed_robotics/JointSetSpeedPos.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_JOINTSETSPEEDPOS_H
#define SEED_ROBOTICS_MESSAGE_JOINTSETSPEEDPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace seed_robotics
{
template <class ContainerAllocator>
struct JointSetSpeedPos_
{
  typedef JointSetSpeedPos_<ContainerAllocator> Type;

  JointSetSpeedPos_()
    : name()
    , target_pos(0)
    , target_speed(0)  {
    }
  JointSetSpeedPos_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , target_pos(0)
    , target_speed(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint16_t _target_pos_type;
  _target_pos_type target_pos;

   typedef int16_t _target_speed_type;
  _target_speed_type target_speed;





  typedef boost::shared_ptr< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> const> ConstPtr;

}; // struct JointSetSpeedPos_

typedef ::seed_robotics::JointSetSpeedPos_<std::allocator<void> > JointSetSpeedPos;

typedef boost::shared_ptr< ::seed_robotics::JointSetSpeedPos > JointSetSpeedPosPtr;
typedef boost::shared_ptr< ::seed_robotics::JointSetSpeedPos const> JointSetSpeedPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seed_robotics::JointSetSpeedPos_<ContainerAllocator1> & lhs, const ::seed_robotics::JointSetSpeedPos_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.target_pos == rhs.target_pos &&
    lhs.target_speed == rhs.target_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seed_robotics::JointSetSpeedPos_<ContainerAllocator1> & lhs, const ::seed_robotics::JointSetSpeedPos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seed_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "081224d8d07c92db7062a286ebd648c5";
  }

  static const char* value(const ::seed_robotics::JointSetSpeedPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x081224d8d07c92dbULL;
  static const uint64_t static_value2 = 0x7062a286ebd648c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_robotics/JointSetSpeedPos";
  }

  static const char* value(const ::seed_robotics::JointSetSpeedPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"uint16 target_pos\n"
"int16 target_speed\n"
;
  }

  static const char* value(const ::seed_robotics::JointSetSpeedPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.target_pos);
      stream.next(m.target_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointSetSpeedPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seed_robotics::JointSetSpeedPos_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "target_pos: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.target_pos);
    s << indent << "target_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.target_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_JOINTSETSPEEDPOS_H
