// Generated by gencpp from file seed_robotics/JointListSetSpeedPos.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_JOINTLISTSETSPEEDPOS_H
#define SEED_ROBOTICS_MESSAGE_JOINTLISTSETSPEEDPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <seed_robotics/JointSetSpeedPos.h>

namespace seed_robotics
{
template <class ContainerAllocator>
struct JointListSetSpeedPos_
{
  typedef JointListSetSpeedPos_<ContainerAllocator> Type;

  JointListSetSpeedPos_()
    : joints()  {
    }
  JointListSetSpeedPos_(const ContainerAllocator& _alloc)
    : joints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> >::other >  _joints_type;
  _joints_type joints;





  typedef boost::shared_ptr< ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator> const> ConstPtr;

}; // struct JointListSetSpeedPos_

typedef ::seed_robotics::JointListSetSpeedPos_<std::allocator<void> > JointListSetSpeedPos;

typedef boost::shared_ptr< ::seed_robotics::JointListSetSpeedPos > JointListSetSpeedPosPtr;
typedef boost::shared_ptr< ::seed_robotics::JointListSetSpeedPos const> JointListSetSpeedPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator1> & lhs, const ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator2> & rhs)
{
  return lhs.joints == rhs.joints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator1> & lhs, const ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seed_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d110ce7073a027c2e8fa43d4d7e9a4ca";
  }

  static const char* value(const ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd110ce7073a027c2ULL;
  static const uint64_t static_value2 = 0xe8fa43d4d7e9a4caULL;
};

template<class ContainerAllocator>
struct DataType< ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_robotics/JointListSetSpeedPos";
  }

  static const char* value(const ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_robotics/JointSetSpeedPos[] joints\n"
"\n"
"================================================================================\n"
"MSG: seed_robotics/JointSetSpeedPos\n"
"string name\n"
"uint16 target_pos\n"
"int16 target_speed\n"
;
  }

  static const char* value(const ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointListSetSpeedPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seed_robotics::JointListSetSpeedPos_<ContainerAllocator>& v)
  {
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::seed_robotics::JointSetSpeedPos_<ContainerAllocator> >::stream(s, indent + "    ", v.joints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_JOINTLISTSETSPEEDPOS_H
