// Generated by gencpp from file seed_robotics/ListClearHWError.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_LISTCLEARHWERROR_H
#define SEED_ROBOTICS_MESSAGE_LISTCLEARHWERROR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <seed_robotics/ClearHWError.h>

namespace seed_robotics
{
template <class ContainerAllocator>
struct ListClearHWError_
{
  typedef ListClearHWError_<ContainerAllocator> Type;

  ListClearHWError_()
    : length(0)
    , joints()  {
    }
  ListClearHWError_(const ContainerAllocator& _alloc)
    : length(0)
    , joints(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _length_type;
  _length_type length;

   typedef std::vector< ::seed_robotics::ClearHWError_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::seed_robotics::ClearHWError_<ContainerAllocator> >::other >  _joints_type;
  _joints_type joints;





  typedef boost::shared_ptr< ::seed_robotics::ListClearHWError_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seed_robotics::ListClearHWError_<ContainerAllocator> const> ConstPtr;

}; // struct ListClearHWError_

typedef ::seed_robotics::ListClearHWError_<std::allocator<void> > ListClearHWError;

typedef boost::shared_ptr< ::seed_robotics::ListClearHWError > ListClearHWErrorPtr;
typedef boost::shared_ptr< ::seed_robotics::ListClearHWError const> ListClearHWErrorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seed_robotics::ListClearHWError_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seed_robotics::ListClearHWError_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seed_robotics::ListClearHWError_<ContainerAllocator1> & lhs, const ::seed_robotics::ListClearHWError_<ContainerAllocator2> & rhs)
{
  return lhs.length == rhs.length &&
    lhs.joints == rhs.joints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seed_robotics::ListClearHWError_<ContainerAllocator1> & lhs, const ::seed_robotics::ListClearHWError_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seed_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::ListClearHWError_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::ListClearHWError_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::ListClearHWError_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::ListClearHWError_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::ListClearHWError_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::ListClearHWError_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seed_robotics::ListClearHWError_<ContainerAllocator> >
{
  static const char* value()
  {
    return "958e71b9000541067274a36d79e8291e";
  }

  static const char* value(const ::seed_robotics::ListClearHWError_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x958e71b900054106ULL;
  static const uint64_t static_value2 = 0x7274a36d79e8291eULL;
};

template<class ContainerAllocator>
struct DataType< ::seed_robotics::ListClearHWError_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_robotics/ListClearHWError";
  }

  static const char* value(const ::seed_robotics::ListClearHWError_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seed_robotics::ListClearHWError_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 length\n"
"seed_robotics/ClearHWError[] joints\n"
"\n"
"================================================================================\n"
"MSG: seed_robotics/ClearHWError\n"
"string name\n"
;
  }

  static const char* value(const ::seed_robotics::ListClearHWError_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seed_robotics::ListClearHWError_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.length);
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListClearHWError_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seed_robotics::ListClearHWError_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seed_robotics::ListClearHWError_<ContainerAllocator>& v)
  {
    s << indent << "length: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.length);
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::seed_robotics::ClearHWError_<ContainerAllocator> >::stream(s, indent + "    ", v.joints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_LISTCLEARHWERROR_H
