// Generated by gencpp from file seed_robotics/SetGoalVelocity.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_SETGOALVELOCITY_H
#define SEED_ROBOTICS_MESSAGE_SETGOALVELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace seed_robotics
{
template <class ContainerAllocator>
struct SetGoalVelocity_
{
  typedef SetGoalVelocity_<ContainerAllocator> Type;

  SetGoalVelocity_()
    : id(0)
    , goal_velocity(0)  {
    }
  SetGoalVelocity_(const ContainerAllocator& _alloc)
    : id(0)
    , goal_velocity(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef int16_t _goal_velocity_type;
  _goal_velocity_type goal_velocity;





  typedef boost::shared_ptr< ::seed_robotics::SetGoalVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seed_robotics::SetGoalVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct SetGoalVelocity_

typedef ::seed_robotics::SetGoalVelocity_<std::allocator<void> > SetGoalVelocity;

typedef boost::shared_ptr< ::seed_robotics::SetGoalVelocity > SetGoalVelocityPtr;
typedef boost::shared_ptr< ::seed_robotics::SetGoalVelocity const> SetGoalVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seed_robotics::SetGoalVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seed_robotics::SetGoalVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seed_robotics::SetGoalVelocity_<ContainerAllocator1> & lhs, const ::seed_robotics::SetGoalVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.goal_velocity == rhs.goal_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seed_robotics::SetGoalVelocity_<ContainerAllocator1> & lhs, const ::seed_robotics::SetGoalVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seed_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::SetGoalVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::SetGoalVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::SetGoalVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::SetGoalVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::SetGoalVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::SetGoalVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seed_robotics::SetGoalVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c16c2214d42fb8949a3d64721f3982d";
  }

  static const char* value(const ::seed_robotics::SetGoalVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c16c2214d42fb89ULL;
  static const uint64_t static_value2 = 0x49a3d64721f3982dULL;
};

template<class ContainerAllocator>
struct DataType< ::seed_robotics::SetGoalVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_robotics/SetGoalVelocity";
  }

  static const char* value(const ::seed_robotics::SetGoalVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seed_robotics::SetGoalVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"int16 goal_velocity\n"
;
  }

  static const char* value(const ::seed_robotics::SetGoalVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seed_robotics::SetGoalVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.goal_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGoalVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seed_robotics::SetGoalVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seed_robotics::SetGoalVelocity_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "goal_velocity: ";
    Printer<int16_t>::stream(s, indent + "  ", v.goal_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_SETGOALVELOCITY_H
