// Generated by gencpp from file seed_robotics/SetGoalPosition.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_SETGOALPOSITION_H
#define SEED_ROBOTICS_MESSAGE_SETGOALPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace seed_robotics
{
template <class ContainerAllocator>
struct SetGoalPosition_
{
  typedef SetGoalPosition_<ContainerAllocator> Type;

  SetGoalPosition_()
    : id(0)
    , goal_position(0)  {
    }
  SetGoalPosition_(const ContainerAllocator& _alloc)
    : id(0)
    , goal_position(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef int16_t _goal_position_type;
  _goal_position_type goal_position;





  typedef boost::shared_ptr< ::seed_robotics::SetGoalPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seed_robotics::SetGoalPosition_<ContainerAllocator> const> ConstPtr;

}; // struct SetGoalPosition_

typedef ::seed_robotics::SetGoalPosition_<std::allocator<void> > SetGoalPosition;

typedef boost::shared_ptr< ::seed_robotics::SetGoalPosition > SetGoalPositionPtr;
typedef boost::shared_ptr< ::seed_robotics::SetGoalPosition const> SetGoalPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seed_robotics::SetGoalPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seed_robotics::SetGoalPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seed_robotics::SetGoalPosition_<ContainerAllocator1> & lhs, const ::seed_robotics::SetGoalPosition_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.goal_position == rhs.goal_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seed_robotics::SetGoalPosition_<ContainerAllocator1> & lhs, const ::seed_robotics::SetGoalPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seed_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::SetGoalPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::SetGoalPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::SetGoalPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::SetGoalPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::SetGoalPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::SetGoalPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seed_robotics::SetGoalPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "660418f6d1f690fc600a479e31cb5227";
  }

  static const char* value(const ::seed_robotics::SetGoalPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x660418f6d1f690fcULL;
  static const uint64_t static_value2 = 0x600a479e31cb5227ULL;
};

template<class ContainerAllocator>
struct DataType< ::seed_robotics::SetGoalPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_robotics/SetGoalPosition";
  }

  static const char* value(const ::seed_robotics::SetGoalPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seed_robotics::SetGoalPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"int16 goal_position\n"
;
  }

  static const char* value(const ::seed_robotics::SetGoalPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seed_robotics::SetGoalPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.goal_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGoalPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seed_robotics::SetGoalPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seed_robotics::SetGoalPosition_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "goal_position: ";
    Printer<int16_t>::stream(s, indent + "  ", v.goal_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_SETGOALPOSITION_H
