// Generated by gencpp from file seed_robotics/SetGoalProfileVelocity.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_SETGOALPROFILEVELOCITY_H
#define SEED_ROBOTICS_MESSAGE_SETGOALPROFILEVELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace seed_robotics
{
template <class ContainerAllocator>
struct SetGoalProfileVelocity_
{
  typedef SetGoalProfileVelocity_<ContainerAllocator> Type;

  SetGoalProfileVelocity_()
    : id(0)
    , goal_profile_velocity(0)  {
    }
  SetGoalProfileVelocity_(const ContainerAllocator& _alloc)
    : id(0)
    , goal_profile_velocity(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef int32_t _goal_profile_velocity_type;
  _goal_profile_velocity_type goal_profile_velocity;





  typedef boost::shared_ptr< ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct SetGoalProfileVelocity_

typedef ::seed_robotics::SetGoalProfileVelocity_<std::allocator<void> > SetGoalProfileVelocity;

typedef boost::shared_ptr< ::seed_robotics::SetGoalProfileVelocity > SetGoalProfileVelocityPtr;
typedef boost::shared_ptr< ::seed_robotics::SetGoalProfileVelocity const> SetGoalProfileVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator1> & lhs, const ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.goal_profile_velocity == rhs.goal_profile_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator1> & lhs, const ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seed_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46b70f7b9e0160279323583cbdf16e19";
  }

  static const char* value(const ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46b70f7b9e016027ULL;
  static const uint64_t static_value2 = 0x9323583cbdf16e19ULL;
};

template<class ContainerAllocator>
struct DataType< ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_robotics/SetGoalProfileVelocity";
  }

  static const char* value(const ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"int32 goal_profile_velocity\n"
;
  }

  static const char* value(const ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.goal_profile_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGoalProfileVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seed_robotics::SetGoalProfileVelocity_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "goal_profile_velocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.goal_profile_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_SETGOALPROFILEVELOCITY_H
