// Generated by gencpp from file seed_robotics/SetShutdownCond.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_SETSHUTDOWNCOND_H
#define SEED_ROBOTICS_MESSAGE_SETSHUTDOWNCOND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace seed_robotics
{
template <class ContainerAllocator>
struct SetShutdownCond_
{
  typedef SetShutdownCond_<ContainerAllocator> Type;

  SetShutdownCond_()
    : name()
    , temperature(false)
    , overload(false)  {
    }
  SetShutdownCond_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , temperature(false)
    , overload(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _temperature_type;
  _temperature_type temperature;

   typedef uint8_t _overload_type;
  _overload_type overload;





  typedef boost::shared_ptr< ::seed_robotics::SetShutdownCond_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seed_robotics::SetShutdownCond_<ContainerAllocator> const> ConstPtr;

}; // struct SetShutdownCond_

typedef ::seed_robotics::SetShutdownCond_<std::allocator<void> > SetShutdownCond;

typedef boost::shared_ptr< ::seed_robotics::SetShutdownCond > SetShutdownCondPtr;
typedef boost::shared_ptr< ::seed_robotics::SetShutdownCond const> SetShutdownCondConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seed_robotics::SetShutdownCond_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seed_robotics::SetShutdownCond_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seed_robotics::SetShutdownCond_<ContainerAllocator1> & lhs, const ::seed_robotics::SetShutdownCond_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.temperature == rhs.temperature &&
    lhs.overload == rhs.overload;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seed_robotics::SetShutdownCond_<ContainerAllocator1> & lhs, const ::seed_robotics::SetShutdownCond_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seed_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::SetShutdownCond_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seed_robotics::SetShutdownCond_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::SetShutdownCond_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seed_robotics::SetShutdownCond_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::SetShutdownCond_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seed_robotics::SetShutdownCond_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seed_robotics::SetShutdownCond_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b50d1b8fda73a468067ba7e8581dfde8";
  }

  static const char* value(const ::seed_robotics::SetShutdownCond_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb50d1b8fda73a468ULL;
  static const uint64_t static_value2 = 0x067ba7e8581dfde8ULL;
};

template<class ContainerAllocator>
struct DataType< ::seed_robotics::SetShutdownCond_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seed_robotics/SetShutdownCond";
  }

  static const char* value(const ::seed_robotics::SetShutdownCond_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seed_robotics::SetShutdownCond_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"bool temperature\n"
"bool overload\n"
;
  }

  static const char* value(const ::seed_robotics::SetShutdownCond_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seed_robotics::SetShutdownCond_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.temperature);
      stream.next(m.overload);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetShutdownCond_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seed_robotics::SetShutdownCond_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seed_robotics::SetShutdownCond_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "temperature: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.temperature);
    s << indent << "overload: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.overload);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_SETSHUTDOWNCOND_H
