// Generated by gencpp from file seed_robotics/SyncGetPosition.msg
// DO NOT EDIT!


#ifndef SEED_ROBOTICS_MESSAGE_SYNCGETPOSITION_H
#define SEED_ROBOTICS_MESSAGE_SYNCGETPOSITION_H

#include <ros/service_traits.h>


#include <seed_robotics/SyncGetPositionRequest.h>
#include <seed_robotics/SyncGetPositionResponse.h>


namespace seed_robotics
{

struct SyncGetPosition
{

typedef SyncGetPositionRequest Request;
typedef SyncGetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SyncGetPosition
} // namespace seed_robotics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::seed_robotics::SyncGetPosition > {
  static const char* value()
  {
    return "4a5a90af26ce6360c45e1980f134941b";
  }

  static const char* value(const ::seed_robotics::SyncGetPosition&) { return value(); }
};

template<>
struct DataType< ::seed_robotics::SyncGetPosition > {
  static const char* value()
  {
    return "seed_robotics/SyncGetPosition";
  }

  static const char* value(const ::seed_robotics::SyncGetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::seed_robotics::SyncGetPositionRequest> should match
// service_traits::MD5Sum< ::seed_robotics::SyncGetPosition >
template<>
struct MD5Sum< ::seed_robotics::SyncGetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::SyncGetPosition >::value();
  }
  static const char* value(const ::seed_robotics::SyncGetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::SyncGetPositionRequest> should match
// service_traits::DataType< ::seed_robotics::SyncGetPosition >
template<>
struct DataType< ::seed_robotics::SyncGetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::SyncGetPosition >::value();
  }
  static const char* value(const ::seed_robotics::SyncGetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::seed_robotics::SyncGetPositionResponse> should match
// service_traits::MD5Sum< ::seed_robotics::SyncGetPosition >
template<>
struct MD5Sum< ::seed_robotics::SyncGetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::seed_robotics::SyncGetPosition >::value();
  }
  static const char* value(const ::seed_robotics::SyncGetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::seed_robotics::SyncGetPositionResponse> should match
// service_traits::DataType< ::seed_robotics::SyncGetPosition >
template<>
struct DataType< ::seed_robotics::SyncGetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::seed_robotics::SyncGetPosition >::value();
  }
  static const char* value(const ::seed_robotics::SyncGetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEED_ROBOTICS_MESSAGE_SYNCGETPOSITION_H
