(cl:defpackage seed_robotics-msg
  (:use )
  (:export
   "<ALLJOINTS>"
   "ALLJOINTS"
   "<ALLMAINBOARDS>"
   "ALLMAINBOARDS"
   "<CLEARHWERROR>"
   "CLEARHWERROR"
   "<JOINTLISTSETSPEEDPOS>"
   "JOINTLISTSETSPEEDPOS"
   "<JOINTLISTSETSTIFFNESS>"
   "JOINTLISTSETSTIFFNESS"
   "<JOINTSETSPEEDPOS>"
   "JOINTSETSPEEDPOS"
   "<LONEJOINT>"
   "LONEJOINT"
   "<LONEMAINBOARD>"
   "LONEMAINBOARD"
   "<SETSHUTDOWNCOND>"
   "SETSHUTDOWNCOND"
   "<SETSTIFFNESS>"
   "SETSTIFFNESS"
  ))

