// Generated by gencpp from file sensor_pkg/AllSensors.msg
// DO NOT EDIT!


#ifndef SENSOR_PKG_MESSAGE_ALLSENSORS_H
#define SENSOR_PKG_MESSAGE_ALLSENSORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_pkg/lone_sensor.h>

namespace sensor_pkg
{
template <class ContainerAllocator>
struct AllSensors_
{
  typedef AllSensors_<ContainerAllocator> Type;

  AllSensors_()
    : header()
    , length(0)
    , data()  {
    }
  AllSensors_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , length(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _length_type;
  _length_type length;

   typedef std::vector< ::sensor_pkg::lone_sensor_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_pkg::lone_sensor_<ContainerAllocator> >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::sensor_pkg::AllSensors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_pkg::AllSensors_<ContainerAllocator> const> ConstPtr;

}; // struct AllSensors_

typedef ::sensor_pkg::AllSensors_<std::allocator<void> > AllSensors;

typedef boost::shared_ptr< ::sensor_pkg::AllSensors > AllSensorsPtr;
typedef boost::shared_ptr< ::sensor_pkg::AllSensors const> AllSensorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_pkg::AllSensors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_pkg::AllSensors_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_pkg::AllSensors_<ContainerAllocator1> & lhs, const ::sensor_pkg::AllSensors_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.length == rhs.length &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_pkg::AllSensors_<ContainerAllocator1> & lhs, const ::sensor_pkg::AllSensors_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensor_pkg::AllSensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_pkg::AllSensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_pkg::AllSensors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_pkg::AllSensors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_pkg::AllSensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_pkg::AllSensors_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_pkg::AllSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "924a629e89d5d37257a3c93c544dec03";
  }

  static const char* value(const ::sensor_pkg::AllSensors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x924a629e89d5d372ULL;
  static const uint64_t static_value2 = 0x57a3c93c544dec03ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_pkg::AllSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_pkg/AllSensors";
  }

  static const char* value(const ::sensor_pkg::AllSensors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_pkg::AllSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 length\n"
"sensor_pkg/lone_sensor[] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_pkg/lone_sensor\n"
"int8 id\n"
"int64 fx\n"
"int64 fy\n"
"int64 fz\n"
"float64 abs\n"
"float64 yaw\n"
"float64 pitch\n"
"bool is_present\n"
"bool is_3D\n"
;
  }

  static const char* value(const ::sensor_pkg::AllSensors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_pkg::AllSensors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.length);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AllSensors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_pkg::AllSensors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_pkg::AllSensors_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "length: ";
    Printer<int8_t>::stream(s, indent + "  ", v.length);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_pkg::lone_sensor_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_PKG_MESSAGE_ALLSENSORS_H
